<?php
/**
 * CreativeVideo1pas
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CreativeVideo1pas Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CreativeVideo1pas implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Creative_Video_1pas';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'float',
        'name' => 'string',
        'user_id' => 'float',
        'active' => 'float',
        'macros_custom_data' => 'string',
        'adomain' => 'string',
        'video_attachment' => 'string',
        'video_clickthrough' => 'string',
        'is_skippable' => 'bool',
        'username' => 'string',
        'approvals' => '\OpenAPI\Client\Model\Approval[]',
        'created' => 'int',
        'updated' => 'int',
        'subdomain_alias' => 'string',
        'iab_attr' => 'float[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'user_id' => null,
        'active' => null,
        'macros_custom_data' => null,
        'adomain' => null,
        'video_attachment' => null,
        'video_clickthrough' => null,
        'is_skippable' => null,
        'username' => null,
        'approvals' => null,
        'created' => null,
        'updated' => null,
        'subdomain_alias' => null,
        'iab_attr' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'user_id' => 'user_id',
        'active' => 'active',
        'macros_custom_data' => 'macros_custom_data',
        'adomain' => 'adomain',
        'video_attachment' => 'video_attachment',
        'video_clickthrough' => 'video_clickthrough',
        'is_skippable' => 'is_skippable',
        'username' => 'username',
        'approvals' => 'approvals',
        'created' => 'created',
        'updated' => 'updated',
        'subdomain_alias' => 'subdomain_alias',
        'iab_attr' => 'iab_attr'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'user_id' => 'setUserId',
        'active' => 'setActive',
        'macros_custom_data' => 'setMacrosCustomData',
        'adomain' => 'setAdomain',
        'video_attachment' => 'setVideoAttachment',
        'video_clickthrough' => 'setVideoClickthrough',
        'is_skippable' => 'setIsSkippable',
        'username' => 'setUsername',
        'approvals' => 'setApprovals',
        'created' => 'setCreated',
        'updated' => 'setUpdated',
        'subdomain_alias' => 'setSubdomainAlias',
        'iab_attr' => 'setIabAttr'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'user_id' => 'getUserId',
        'active' => 'getActive',
        'macros_custom_data' => 'getMacrosCustomData',
        'adomain' => 'getAdomain',
        'video_attachment' => 'getVideoAttachment',
        'video_clickthrough' => 'getVideoClickthrough',
        'is_skippable' => 'getIsSkippable',
        'username' => 'getUsername',
        'approvals' => 'getApprovals',
        'created' => 'getCreated',
        'updated' => 'getUpdated',
        'subdomain_alias' => 'getSubdomainAlias',
        'iab_attr' => 'getIabAttr'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['active'] = isset($data['active']) ? $data['active'] : null;
        $this->container['macros_custom_data'] = isset($data['macros_custom_data']) ? $data['macros_custom_data'] : null;
        $this->container['adomain'] = isset($data['adomain']) ? $data['adomain'] : null;
        $this->container['video_attachment'] = isset($data['video_attachment']) ? $data['video_attachment'] : null;
        $this->container['video_clickthrough'] = isset($data['video_clickthrough']) ? $data['video_clickthrough'] : null;
        $this->container['is_skippable'] = isset($data['is_skippable']) ? $data['is_skippable'] : null;
        $this->container['username'] = isset($data['username']) ? $data['username'] : null;
        $this->container['approvals'] = isset($data['approvals']) ? $data['approvals'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['updated'] = isset($data['updated']) ? $data['updated'] : null;
        $this->container['subdomain_alias'] = isset($data['subdomain_alias']) ? $data['subdomain_alias'] : null;
        $this->container['iab_attr'] = isset($data['iab_attr']) ? $data['iab_attr'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['macros_custom_data']) && (mb_strlen($this->container['macros_custom_data']) > 500)) {
            $invalidProperties[] = "invalid value for 'macros_custom_data', the character length must be smaller than or equal to 500.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return float|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param float|null $id Creative ID.
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Creative Name.
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return float|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param float|null $user_id User ID.
     *
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets active
     *
     * @return float|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param float|null $active Status. 1 - Active, 0 - Pause. Required. One of the ID values of parameter `statuses` in /constants is added to this parameter.
     *
     * @return $this
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets macros_custom_data
     *
     * @return string|null
     */
    public function getMacrosCustomData()
    {
        return $this->container['macros_custom_data'];
    }

    /**
     * Sets macros_custom_data
     *
     * @param string|null $macros_custom_data You can pass this data upon impression using the [CREATIVE_CUSTOM_DATA] macro.
     *
     * @return $this
     */
    public function setMacrosCustomData($macros_custom_data)
    {
        if (!is_null($macros_custom_data) && (mb_strlen($macros_custom_data) > 500)) {
            throw new \InvalidArgumentException('invalid length for $macros_custom_data when calling CreativeVideo1pas., must be smaller than or equal to 500.');
        }

        $this->container['macros_custom_data'] = $macros_custom_data;

        return $this;
    }

    /**
     * Gets adomain
     *
     * @return string|null
     */
    public function getAdomain()
    {
        return $this->container['adomain'];
    }

    /**
     * Sets adomain
     *
     * @param string|null $adomain Advertiser domain.
     *
     * @return $this
     */
    public function setAdomain($adomain)
    {
        $this->container['adomain'] = $adomain;

        return $this;
    }

    /**
     * Gets video_attachment
     *
     * @return string|null
     */
    public function getVideoAttachment()
    {
        return $this->container['video_attachment'];
    }

    /**
     * Sets video_attachment
     *
     * @param string|null $video_attachment Video to upload. Only '.flv, .mp4, .avi, .wmv, .mov' is allowed
     *
     * @return $this
     */
    public function setVideoAttachment($video_attachment)
    {
        $this->container['video_attachment'] = $video_attachment;

        return $this;
    }

    /**
     * Gets video_clickthrough
     *
     * @return string|null
     */
    public function getVideoClickthrough()
    {
        return $this->container['video_clickthrough'];
    }

    /**
     * Sets video_clickthrough
     *
     * @param string|null $video_clickthrough Video Clickthrough
     *
     * @return $this
     */
    public function setVideoClickthrough($video_clickthrough)
    {
        $this->container['video_clickthrough'] = $video_clickthrough;

        return $this;
    }

    /**
     * Gets is_skippable
     *
     * @return bool|null
     */
    public function getIsSkippable()
    {
        return $this->container['is_skippable'];
    }

    /**
     * Sets is_skippable
     *
     * @param bool|null $is_skippable Video Skippable tracker
     *
     * @return $this
     */
    public function setIsSkippable($is_skippable)
    {
        $this->container['is_skippable'] = $is_skippable;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username User name
     *
     * @return $this
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets approvals
     *
     * @return \OpenAPI\Client\Model\Approval[]|null
     */
    public function getApprovals()
    {
        return $this->container['approvals'];
    }

    /**
     * Sets approvals
     *
     * @param \OpenAPI\Client\Model\Approval[]|null $approvals approvals
     *
     * @return $this
     */
    public function setApprovals($approvals)
    {
        $this->container['approvals'] = $approvals;

        return $this;
    }

    /**
     * Gets created
     *
     * @return int|null
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param int|null $created Created timestamp
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return int|null
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param int|null $updated Updated timestamp
     *
     * @return $this
     */
    public function setUpdated($updated)
    {
        $this->container['updated'] = $updated;

        return $this;
    }

    /**
     * Gets subdomain_alias
     *
     * @return string|null
     */
    public function getSubdomainAlias()
    {
        return $this->container['subdomain_alias'];
    }

    /**
     * Sets subdomain_alias
     *
     * @param string|null $subdomain_alias Users subdomain alias **Only for Root**
     *
     * @return $this
     */
    public function setSubdomainAlias($subdomain_alias)
    {
        $this->container['subdomain_alias'] = $subdomain_alias;

        return $this;
    }

    /**
     * Gets iab_attr
     *
     * @return float[]|null
     */
    public function getIabAttr()
    {
        return $this->container['iab_attr'];
    }

    /**
     * Sets iab_attr
     *
     * @param float[]|null $iab_attr iab_attr
     *
     * @return $this
     */
    public function setIabAttr($iab_attr)
    {
        $this->container['iab_attr'] = $iab_attr;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


