<?php
/**
 * EditCreativeDisplay3pas
 *
 * PHP version 7.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EditCreativeDisplay3pas Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EditCreativeDisplay3pas implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'editCreative_Display_3pas';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'active' => 'float',
        'iab_attr' => 'float[]',
        'size' => 'float',
        'display_width' => 'float',
        'display_height' => 'float',
        'audio' => 'float',
        'html' => 'string',
        'secure_type' => 'float',
        'macros_custom_data' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'name' => null,
        'active' => null,
        'iab_attr' => null,
        'size' => null,
        'display_width' => null,
        'display_height' => null,
        'audio' => null,
        'html' => null,
        'secure_type' => null,
        'macros_custom_data' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'active' => 'active',
        'iab_attr' => 'iab_attr',
        'size' => 'size',
        'display_width' => 'display_width',
        'display_height' => 'display_height',
        'audio' => 'audio',
        'html' => 'html',
        'secure_type' => 'secure_type',
        'macros_custom_data' => 'macros_custom_data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'active' => 'setActive',
        'iab_attr' => 'setIabAttr',
        'size' => 'setSize',
        'display_width' => 'setDisplayWidth',
        'display_height' => 'setDisplayHeight',
        'audio' => 'setAudio',
        'html' => 'setHtml',
        'secure_type' => 'setSecureType',
        'macros_custom_data' => 'setMacrosCustomData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'active' => 'getActive',
        'iab_attr' => 'getIabAttr',
        'size' => 'getSize',
        'display_width' => 'getDisplayWidth',
        'display_height' => 'getDisplayHeight',
        'audio' => 'getAudio',
        'html' => 'getHtml',
        'secure_type' => 'getSecureType',
        'macros_custom_data' => 'getMacrosCustomData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['active'] = isset($data['active']) ? $data['active'] : null;
        $this->container['iab_attr'] = isset($data['iab_attr']) ? $data['iab_attr'] : null;
        $this->container['size'] = isset($data['size']) ? $data['size'] : null;
        $this->container['display_width'] = isset($data['display_width']) ? $data['display_width'] : null;
        $this->container['display_height'] = isset($data['display_height']) ? $data['display_height'] : null;
        $this->container['audio'] = isset($data['audio']) ? $data['audio'] : null;
        $this->container['html'] = isset($data['html']) ? $data['html'] : null;
        $this->container['secure_type'] = isset($data['secure_type']) ? $data['secure_type'] : null;
        $this->container['macros_custom_data'] = isset($data['macros_custom_data']) ? $data['macros_custom_data'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['display_width']) && ($this->container['display_width'] > 1E+4)) {
            $invalidProperties[] = "invalid value for 'display_width', must be smaller than or equal to 1E+4.";
        }

        if (!is_null($this->container['display_width']) && ($this->container['display_width'] < 1)) {
            $invalidProperties[] = "invalid value for 'display_width', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['display_height']) && ($this->container['display_height'] > 1E+4)) {
            $invalidProperties[] = "invalid value for 'display_height', must be smaller than or equal to 1E+4.";
        }

        if (!is_null($this->container['display_height']) && ($this->container['display_height'] < 1)) {
            $invalidProperties[] = "invalid value for 'display_height', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['macros_custom_data']) && (mb_strlen($this->container['macros_custom_data']) > 500)) {
            $invalidProperties[] = "invalid value for 'macros_custom_data', the character length must be smaller than or equal to 500.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Creative Name.
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets active
     *
     * @return float|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param float|null $active Status. 1 - Active, 0 - Pause. Required. One of the ID values of parameter `statuses` in /constants is added to this parameter.
     *
     * @return $this
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets iab_attr
     *
     * @return float[]|null
     */
    public function getIabAttr()
    {
        return $this->container['iab_attr'];
    }

    /**
     * Sets iab_attr
     *
     * @param float[]|null $iab_attr iab_attr
     *
     * @return $this
     */
    public function setIabAttr($iab_attr)
    {
        $this->container['iab_attr'] = $iab_attr;

        return $this;
    }

    /**
     * Gets size
     *
     * @return float|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param float|null $size Dimensions.
     *
     * @return $this
     */
    public function setSize($size)
    {
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets display_width
     *
     * @return float|null
     */
    public function getDisplayWidth()
    {
        return $this->container['display_width'];
    }

    /**
     * Sets display_width
     *
     * @param float|null $display_width Display Width. if size = 0 - Required.
     *
     * @return $this
     */
    public function setDisplayWidth($display_width)
    {

        if (!is_null($display_width) && ($display_width > 1E+4)) {
            throw new \InvalidArgumentException('invalid value for $display_width when calling EditCreativeDisplay3pas., must be smaller than or equal to 1E+4.');
        }

        $this->container['display_width'] = $display_width;

        return $this;
    }

    /**
     * Gets display_height
     *
     * @return float|null
     */
    public function getDisplayHeight()
    {
        return $this->container['display_height'];
    }

    /**
     * Sets display_height
     *
     * @param float|null $display_height Display Height. if size = 0 - Required.
     *
     * @return $this
     */
    public function setDisplayHeight($display_height)
    {

        if (!is_null($display_height) && ($display_height > 1E+4)) {
            throw new \InvalidArgumentException('invalid value for $display_height when calling EditCreativeDisplay3pas., must be smaller than or equal to 1E+4.');
        }

        $this->container['display_height'] = $display_height;

        return $this;
    }

    /**
     * Gets audio
     *
     * @return float|null
     */
    public function getAudio()
    {
        return $this->container['audio'];
    }

    /**
     * Sets audio
     *
     * @param float|null $audio Audio. 1 - yes, 0 - no.
     *
     * @return $this
     */
    public function setAudio($audio)
    {
        $this->container['audio'] = $audio;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html Ad Tag Code.
     *
     * @return $this
     */
    public function setHtml($html)
    {
        $this->container['html'] = $html;

        return $this;
    }

    /**
     * Gets secure_type
     *
     * @return float|null
     */
    public function getSecureType()
    {
        return $this->container['secure_type'];
    }

    /**
     * Sets secure_type
     *
     * @param float|null $secure_type Security.
     *
     * @return $this
     */
    public function setSecureType($secure_type)
    {
        $this->container['secure_type'] = $secure_type;

        return $this;
    }

    /**
     * Gets macros_custom_data
     *
     * @return string|null
     */
    public function getMacrosCustomData()
    {
        return $this->container['macros_custom_data'];
    }

    /**
     * Sets macros_custom_data
     *
     * @param string|null $macros_custom_data You can pass this data upon impression using the [CREATIVE_CUSTOM_DATA] macro.
     *
     * @return $this
     */
    public function setMacrosCustomData($macros_custom_data)
    {
        if (!is_null($macros_custom_data) && (mb_strlen($macros_custom_data) > 500)) {
            throw new \InvalidArgumentException('invalid length for $macros_custom_data when calling EditCreativeDisplay3pas., must be smaller than or equal to 500.');
        }

        $this->container['macros_custom_data'] = $macros_custom_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


