<?php
/**
 * InlineResponse2001
 *
 * PHP version 7.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InlineResponse2001 Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InlineResponse2001 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'checklist_campaign_ad_status' => 'string',
        'checklist_campaign_ad_set_status' => 'string',
        'checklist_campaign_assigned_status' => 'string',
        'checklist_campaign_ad_set_datetime_status' => 'string',
        'checklist_campaign_status' => 'string',
        'checklist_campaign_datetime_status' => 'string',
        'checklist_campaign_budget_status' => 'string',
        'checklist_campaign_advertiser_balance_status' => 'string',
        'checklist_campaign_organization_balance_status' => 'string',
        'checklist_campaign_agency_balance_status' => 'string',
        'checklist_campaign_organization_status' => 'string',
        'checklist_campaign_agency_status' => 'string',
        'checklist_campaign_advertiser_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'checklist_campaign_ad_status' => null,
        'checklist_campaign_ad_set_status' => null,
        'checklist_campaign_assigned_status' => null,
        'checklist_campaign_ad_set_datetime_status' => null,
        'checklist_campaign_status' => null,
        'checklist_campaign_datetime_status' => null,
        'checklist_campaign_budget_status' => null,
        'checklist_campaign_advertiser_balance_status' => null,
        'checklist_campaign_organization_balance_status' => null,
        'checklist_campaign_agency_balance_status' => null,
        'checklist_campaign_organization_status' => null,
        'checklist_campaign_agency_status' => null,
        'checklist_campaign_advertiser_status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'checklist_campaign_ad_status' => 'checklist_campaign_ad_status',
        'checklist_campaign_ad_set_status' => 'checklist_campaign_ad_set_status',
        'checklist_campaign_assigned_status' => 'checklist_campaign_assigned_status',
        'checklist_campaign_ad_set_datetime_status' => 'checklist_campaign_ad_set_datetime_status',
        'checklist_campaign_status' => 'checklist_campaign_status',
        'checklist_campaign_datetime_status' => 'checklist_campaign_datetime_status',
        'checklist_campaign_budget_status' => 'checklist_campaign_budget_status',
        'checklist_campaign_advertiser_balance_status' => 'checklist_campaign_advertiser_balance_status',
        'checklist_campaign_organization_balance_status' => 'checklist_campaign_organization_balance_status',
        'checklist_campaign_agency_balance_status' => 'checklist_campaign_agency_balance_status',
        'checklist_campaign_organization_status' => 'checklist_campaign_organization_status',
        'checklist_campaign_agency_status' => 'checklist_campaign_agency_status',
        'checklist_campaign_advertiser_status' => 'checklist_campaign_advertiser_status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'checklist_campaign_ad_status' => 'setChecklistCampaignAdStatus',
        'checklist_campaign_ad_set_status' => 'setChecklistCampaignAdSetStatus',
        'checklist_campaign_assigned_status' => 'setChecklistCampaignAssignedStatus',
        'checklist_campaign_ad_set_datetime_status' => 'setChecklistCampaignAdSetDatetimeStatus',
        'checklist_campaign_status' => 'setChecklistCampaignStatus',
        'checklist_campaign_datetime_status' => 'setChecklistCampaignDatetimeStatus',
        'checklist_campaign_budget_status' => 'setChecklistCampaignBudgetStatus',
        'checklist_campaign_advertiser_balance_status' => 'setChecklistCampaignAdvertiserBalanceStatus',
        'checklist_campaign_organization_balance_status' => 'setChecklistCampaignOrganizationBalanceStatus',
        'checklist_campaign_agency_balance_status' => 'setChecklistCampaignAgencyBalanceStatus',
        'checklist_campaign_organization_status' => 'setChecklistCampaignOrganizationStatus',
        'checklist_campaign_agency_status' => 'setChecklistCampaignAgencyStatus',
        'checklist_campaign_advertiser_status' => 'setChecklistCampaignAdvertiserStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'checklist_campaign_ad_status' => 'getChecklistCampaignAdStatus',
        'checklist_campaign_ad_set_status' => 'getChecklistCampaignAdSetStatus',
        'checklist_campaign_assigned_status' => 'getChecklistCampaignAssignedStatus',
        'checklist_campaign_ad_set_datetime_status' => 'getChecklistCampaignAdSetDatetimeStatus',
        'checklist_campaign_status' => 'getChecklistCampaignStatus',
        'checklist_campaign_datetime_status' => 'getChecklistCampaignDatetimeStatus',
        'checklist_campaign_budget_status' => 'getChecklistCampaignBudgetStatus',
        'checklist_campaign_advertiser_balance_status' => 'getChecklistCampaignAdvertiserBalanceStatus',
        'checklist_campaign_organization_balance_status' => 'getChecklistCampaignOrganizationBalanceStatus',
        'checklist_campaign_agency_balance_status' => 'getChecklistCampaignAgencyBalanceStatus',
        'checklist_campaign_organization_status' => 'getChecklistCampaignOrganizationStatus',
        'checklist_campaign_agency_status' => 'getChecklistCampaignAgencyStatus',
        'checklist_campaign_advertiser_status' => 'getChecklistCampaignAdvertiserStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const CHECKLIST_CAMPAIGN_AD_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_AD_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_AD_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_AD_SET_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_AD_SET_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_AD_SET_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_ASSIGNED_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_ASSIGNED_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_ASSIGNED_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_AD_SET_DATETIME_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_AD_SET_DATETIME_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_AD_SET_DATETIME_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_DATETIME_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_DATETIME_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_DATETIME_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_BUDGET_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_BUDGET_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_BUDGET_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_ADVERTISER_BALANCE_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_ADVERTISER_BALANCE_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_ADVERTISER_BALANCE_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_ORGANIZATION_BALANCE_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_ORGANIZATION_BALANCE_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_ORGANIZATION_BALANCE_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_AGENCY_BALANCE_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_AGENCY_BALANCE_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_AGENCY_BALANCE_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_ORGANIZATION_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_ORGANIZATION_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_ORGANIZATION_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_AGENCY_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_AGENCY_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_AGENCY_STATUS_PARTIAL_ACTIVE = 'partial_active';
    const CHECKLIST_CAMPAIGN_ADVERTISER_STATUS_ACTIVE = 'active';
    const CHECKLIST_CAMPAIGN_ADVERTISER_STATUS_INACTIVE = 'inactive';
    const CHECKLIST_CAMPAIGN_ADVERTISER_STATUS_PARTIAL_ACTIVE = 'partial_active';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAdStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_AD_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_AD_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_AD_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAdSetStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_AD_SET_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_AD_SET_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_AD_SET_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAssignedStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_ASSIGNED_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_ASSIGNED_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_ASSIGNED_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAdSetDatetimeStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_AD_SET_DATETIME_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_AD_SET_DATETIME_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_AD_SET_DATETIME_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignDatetimeStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_DATETIME_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_DATETIME_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_DATETIME_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignBudgetStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_BUDGET_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_BUDGET_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_BUDGET_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAdvertiserBalanceStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_ADVERTISER_BALANCE_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_ADVERTISER_BALANCE_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_ADVERTISER_BALANCE_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignOrganizationBalanceStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_ORGANIZATION_BALANCE_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_ORGANIZATION_BALANCE_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_ORGANIZATION_BALANCE_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAgencyBalanceStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_AGENCY_BALANCE_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_AGENCY_BALANCE_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_AGENCY_BALANCE_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignOrganizationStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_ORGANIZATION_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_ORGANIZATION_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_ORGANIZATION_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAgencyStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_AGENCY_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_AGENCY_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_AGENCY_STATUS_PARTIAL_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecklistCampaignAdvertiserStatusAllowableValues()
    {
        return [
            self::CHECKLIST_CAMPAIGN_ADVERTISER_STATUS_ACTIVE,
            self::CHECKLIST_CAMPAIGN_ADVERTISER_STATUS_INACTIVE,
            self::CHECKLIST_CAMPAIGN_ADVERTISER_STATUS_PARTIAL_ACTIVE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['checklist_campaign_ad_status'] = isset($data['checklist_campaign_ad_status']) ? $data['checklist_campaign_ad_status'] : null;
        $this->container['checklist_campaign_ad_set_status'] = isset($data['checklist_campaign_ad_set_status']) ? $data['checklist_campaign_ad_set_status'] : null;
        $this->container['checklist_campaign_assigned_status'] = isset($data['checklist_campaign_assigned_status']) ? $data['checklist_campaign_assigned_status'] : null;
        $this->container['checklist_campaign_ad_set_datetime_status'] = isset($data['checklist_campaign_ad_set_datetime_status']) ? $data['checklist_campaign_ad_set_datetime_status'] : null;
        $this->container['checklist_campaign_status'] = isset($data['checklist_campaign_status']) ? $data['checklist_campaign_status'] : null;
        $this->container['checklist_campaign_datetime_status'] = isset($data['checklist_campaign_datetime_status']) ? $data['checklist_campaign_datetime_status'] : null;
        $this->container['checklist_campaign_budget_status'] = isset($data['checklist_campaign_budget_status']) ? $data['checklist_campaign_budget_status'] : null;
        $this->container['checklist_campaign_advertiser_balance_status'] = isset($data['checklist_campaign_advertiser_balance_status']) ? $data['checklist_campaign_advertiser_balance_status'] : null;
        $this->container['checklist_campaign_organization_balance_status'] = isset($data['checklist_campaign_organization_balance_status']) ? $data['checklist_campaign_organization_balance_status'] : null;
        $this->container['checklist_campaign_agency_balance_status'] = isset($data['checklist_campaign_agency_balance_status']) ? $data['checklist_campaign_agency_balance_status'] : null;
        $this->container['checklist_campaign_organization_status'] = isset($data['checklist_campaign_organization_status']) ? $data['checklist_campaign_organization_status'] : null;
        $this->container['checklist_campaign_agency_status'] = isset($data['checklist_campaign_agency_status']) ? $data['checklist_campaign_agency_status'] : null;
        $this->container['checklist_campaign_advertiser_status'] = isset($data['checklist_campaign_advertiser_status']) ? $data['checklist_campaign_advertiser_status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getChecklistCampaignAdStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_ad_status']) && !in_array($this->container['checklist_campaign_ad_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_ad_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignAdSetStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_ad_set_status']) && !in_array($this->container['checklist_campaign_ad_set_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_ad_set_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignAssignedStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_assigned_status']) && !in_array($this->container['checklist_campaign_assigned_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_assigned_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignAdSetDatetimeStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_ad_set_datetime_status']) && !in_array($this->container['checklist_campaign_ad_set_datetime_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_ad_set_datetime_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_status']) && !in_array($this->container['checklist_campaign_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignDatetimeStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_datetime_status']) && !in_array($this->container['checklist_campaign_datetime_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_datetime_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignBudgetStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_budget_status']) && !in_array($this->container['checklist_campaign_budget_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_budget_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignAdvertiserBalanceStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_advertiser_balance_status']) && !in_array($this->container['checklist_campaign_advertiser_balance_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_advertiser_balance_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignOrganizationBalanceStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_organization_balance_status']) && !in_array($this->container['checklist_campaign_organization_balance_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_organization_balance_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignAgencyBalanceStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_agency_balance_status']) && !in_array($this->container['checklist_campaign_agency_balance_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_agency_balance_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignOrganizationStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_organization_status']) && !in_array($this->container['checklist_campaign_organization_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_organization_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignAgencyStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_agency_status']) && !in_array($this->container['checklist_campaign_agency_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_agency_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChecklistCampaignAdvertiserStatusAllowableValues();
        if (!is_null($this->container['checklist_campaign_advertiser_status']) && !in_array($this->container['checklist_campaign_advertiser_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'checklist_campaign_advertiser_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets checklist_campaign_ad_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAdStatus()
    {
        return $this->container['checklist_campaign_ad_status'];
    }

    /**
     * Sets checklist_campaign_ad_status
     *
     * @param string|null $checklist_campaign_ad_status checklist_campaign_ad_status
     *
     * @return $this
     */
    public function setChecklistCampaignAdStatus($checklist_campaign_ad_status)
    {
        $allowedValues = $this->getChecklistCampaignAdStatusAllowableValues();
        if (!is_null($checklist_campaign_ad_status) && !in_array($checklist_campaign_ad_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_ad_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_ad_status'] = $checklist_campaign_ad_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_ad_set_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAdSetStatus()
    {
        return $this->container['checklist_campaign_ad_set_status'];
    }

    /**
     * Sets checklist_campaign_ad_set_status
     *
     * @param string|null $checklist_campaign_ad_set_status checklist_campaign_ad_set_status
     *
     * @return $this
     */
    public function setChecklistCampaignAdSetStatus($checklist_campaign_ad_set_status)
    {
        $allowedValues = $this->getChecklistCampaignAdSetStatusAllowableValues();
        if (!is_null($checklist_campaign_ad_set_status) && !in_array($checklist_campaign_ad_set_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_ad_set_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_ad_set_status'] = $checklist_campaign_ad_set_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_assigned_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAssignedStatus()
    {
        return $this->container['checklist_campaign_assigned_status'];
    }

    /**
     * Sets checklist_campaign_assigned_status
     *
     * @param string|null $checklist_campaign_assigned_status checklist_campaign_assigned_status
     *
     * @return $this
     */
    public function setChecklistCampaignAssignedStatus($checklist_campaign_assigned_status)
    {
        $allowedValues = $this->getChecklistCampaignAssignedStatusAllowableValues();
        if (!is_null($checklist_campaign_assigned_status) && !in_array($checklist_campaign_assigned_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_assigned_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_assigned_status'] = $checklist_campaign_assigned_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_ad_set_datetime_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAdSetDatetimeStatus()
    {
        return $this->container['checklist_campaign_ad_set_datetime_status'];
    }

    /**
     * Sets checklist_campaign_ad_set_datetime_status
     *
     * @param string|null $checklist_campaign_ad_set_datetime_status checklist_campaign_ad_set_datetime_status
     *
     * @return $this
     */
    public function setChecklistCampaignAdSetDatetimeStatus($checklist_campaign_ad_set_datetime_status)
    {
        $allowedValues = $this->getChecklistCampaignAdSetDatetimeStatusAllowableValues();
        if (!is_null($checklist_campaign_ad_set_datetime_status) && !in_array($checklist_campaign_ad_set_datetime_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_ad_set_datetime_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_ad_set_datetime_status'] = $checklist_campaign_ad_set_datetime_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_status
     *
     * @return string|null
     */
    public function getChecklistCampaignStatus()
    {
        return $this->container['checklist_campaign_status'];
    }

    /**
     * Sets checklist_campaign_status
     *
     * @param string|null $checklist_campaign_status checklist_campaign_status
     *
     * @return $this
     */
    public function setChecklistCampaignStatus($checklist_campaign_status)
    {
        $allowedValues = $this->getChecklistCampaignStatusAllowableValues();
        if (!is_null($checklist_campaign_status) && !in_array($checklist_campaign_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_status'] = $checklist_campaign_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_datetime_status
     *
     * @return string|null
     */
    public function getChecklistCampaignDatetimeStatus()
    {
        return $this->container['checklist_campaign_datetime_status'];
    }

    /**
     * Sets checklist_campaign_datetime_status
     *
     * @param string|null $checklist_campaign_datetime_status checklist_campaign_datetime_status
     *
     * @return $this
     */
    public function setChecklistCampaignDatetimeStatus($checklist_campaign_datetime_status)
    {
        $allowedValues = $this->getChecklistCampaignDatetimeStatusAllowableValues();
        if (!is_null($checklist_campaign_datetime_status) && !in_array($checklist_campaign_datetime_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_datetime_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_datetime_status'] = $checklist_campaign_datetime_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_budget_status
     *
     * @return string|null
     */
    public function getChecklistCampaignBudgetStatus()
    {
        return $this->container['checklist_campaign_budget_status'];
    }

    /**
     * Sets checklist_campaign_budget_status
     *
     * @param string|null $checklist_campaign_budget_status checklist_campaign_budget_status
     *
     * @return $this
     */
    public function setChecklistCampaignBudgetStatus($checklist_campaign_budget_status)
    {
        $allowedValues = $this->getChecklistCampaignBudgetStatusAllowableValues();
        if (!is_null($checklist_campaign_budget_status) && !in_array($checklist_campaign_budget_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_budget_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_budget_status'] = $checklist_campaign_budget_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_advertiser_balance_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAdvertiserBalanceStatus()
    {
        return $this->container['checklist_campaign_advertiser_balance_status'];
    }

    /**
     * Sets checklist_campaign_advertiser_balance_status
     *
     * @param string|null $checklist_campaign_advertiser_balance_status checklist_campaign_advertiser_balance_status
     *
     * @return $this
     */
    public function setChecklistCampaignAdvertiserBalanceStatus($checklist_campaign_advertiser_balance_status)
    {
        $allowedValues = $this->getChecklistCampaignAdvertiserBalanceStatusAllowableValues();
        if (!is_null($checklist_campaign_advertiser_balance_status) && !in_array($checklist_campaign_advertiser_balance_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_advertiser_balance_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_advertiser_balance_status'] = $checklist_campaign_advertiser_balance_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_organization_balance_status
     *
     * @return string|null
     */
    public function getChecklistCampaignOrganizationBalanceStatus()
    {
        return $this->container['checklist_campaign_organization_balance_status'];
    }

    /**
     * Sets checklist_campaign_organization_balance_status
     *
     * @param string|null $checklist_campaign_organization_balance_status checklist_campaign_organization_balance_status
     *
     * @return $this
     */
    public function setChecklistCampaignOrganizationBalanceStatus($checklist_campaign_organization_balance_status)
    {
        $allowedValues = $this->getChecklistCampaignOrganizationBalanceStatusAllowableValues();
        if (!is_null($checklist_campaign_organization_balance_status) && !in_array($checklist_campaign_organization_balance_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_organization_balance_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_organization_balance_status'] = $checklist_campaign_organization_balance_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_agency_balance_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAgencyBalanceStatus()
    {
        return $this->container['checklist_campaign_agency_balance_status'];
    }

    /**
     * Sets checklist_campaign_agency_balance_status
     *
     * @param string|null $checklist_campaign_agency_balance_status checklist_campaign_agency_balance_status
     *
     * @return $this
     */
    public function setChecklistCampaignAgencyBalanceStatus($checklist_campaign_agency_balance_status)
    {
        $allowedValues = $this->getChecklistCampaignAgencyBalanceStatusAllowableValues();
        if (!is_null($checklist_campaign_agency_balance_status) && !in_array($checklist_campaign_agency_balance_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_agency_balance_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_agency_balance_status'] = $checklist_campaign_agency_balance_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_organization_status
     *
     * @return string|null
     */
    public function getChecklistCampaignOrganizationStatus()
    {
        return $this->container['checklist_campaign_organization_status'];
    }

    /**
     * Sets checklist_campaign_organization_status
     *
     * @param string|null $checklist_campaign_organization_status checklist_campaign_organization_status
     *
     * @return $this
     */
    public function setChecklistCampaignOrganizationStatus($checklist_campaign_organization_status)
    {
        $allowedValues = $this->getChecklistCampaignOrganizationStatusAllowableValues();
        if (!is_null($checklist_campaign_organization_status) && !in_array($checklist_campaign_organization_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_organization_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_organization_status'] = $checklist_campaign_organization_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_agency_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAgencyStatus()
    {
        return $this->container['checklist_campaign_agency_status'];
    }

    /**
     * Sets checklist_campaign_agency_status
     *
     * @param string|null $checklist_campaign_agency_status checklist_campaign_agency_status
     *
     * @return $this
     */
    public function setChecklistCampaignAgencyStatus($checklist_campaign_agency_status)
    {
        $allowedValues = $this->getChecklistCampaignAgencyStatusAllowableValues();
        if (!is_null($checklist_campaign_agency_status) && !in_array($checklist_campaign_agency_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_agency_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_agency_status'] = $checklist_campaign_agency_status;

        return $this;
    }

    /**
     * Gets checklist_campaign_advertiser_status
     *
     * @return string|null
     */
    public function getChecklistCampaignAdvertiserStatus()
    {
        return $this->container['checklist_campaign_advertiser_status'];
    }

    /**
     * Sets checklist_campaign_advertiser_status
     *
     * @param string|null $checklist_campaign_advertiser_status checklist_campaign_advertiser_status
     *
     * @return $this
     */
    public function setChecklistCampaignAdvertiserStatus($checklist_campaign_advertiser_status)
    {
        $allowedValues = $this->getChecklistCampaignAdvertiserStatusAllowableValues();
        if (!is_null($checklist_campaign_advertiser_status) && !in_array($checklist_campaign_advertiser_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checklist_campaign_advertiser_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checklist_campaign_advertiser_status'] = $checklist_campaign_advertiser_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


