<?php
/**
 * CreativeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CreativeTest Class Doc Comment
 *
 * @category    Class
 * @description Creative
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreativeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Creative"
     */
    public function testCreative()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "iab_attr"
     */
    public function testPropertyIabAttr()
    {
    }

    /**
     * Test attribute "adomain"
     */
    public function testPropertyAdomain()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "audio"
     */
    public function testPropertyAudio()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "secure_type"
     */
    public function testPropertySecureType()
    {
    }

    /**
     * Test attribute "image_attachment"
     */
    public function testPropertyImageAttachment()
    {
    }

    /**
     * Test attribute "destination_url"
     */
    public function testPropertyDestinationUrl()
    {
    }

    /**
     * Test attribute "call_to_action"
     */
    public function testPropertyCallToAction()
    {
    }

    /**
     * Test attribute "image_attachment_logo"
     */
    public function testPropertyImageAttachmentLogo()
    {
    }

    /**
     * Test attribute "headline"
     */
    public function testPropertyHeadline()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "brand_name"
     */
    public function testPropertyBrandName()
    {
    }

    /**
     * Test attribute "video_attachment"
     */
    public function testPropertyVideoAttachment()
    {
    }

    /**
     * Test attribute "video_api_framework"
     */
    public function testPropertyVideoApiFramework()
    {
    }

    /**
     * Test attribute "vast_type"
     */
    public function testPropertyVastType()
    {
    }

    /**
     * Test attribute "is_1pas"
     */
    public function testPropertyIs1pas()
    {
    }

    /**
     * Test attribute "video_clickthrough"
     */
    public function testPropertyVideoClickthrough()
    {
    }

    /**
     * Test attribute "macros_custom_data"
     */
    public function testPropertyMacrosCustomData()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "approvals"
     */
    public function testPropertyApprovals()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {
    }

    /**
     * Test attribute "subdomain_alias"
     */
    public function testPropertySubdomainAlias()
    {
    }
}
