<?php
/**
 * DspTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * DspTest Class Doc Comment
 *
 * @category    Class
 * @description Dsp
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DspTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Dsp"
     */
    public function testDsp()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "ui_name"
     */
    public function testPropertyUiName()
    {
    }

    /**
     * Test attribute "test_mode"
     */
    public function testPropertyTestMode()
    {
    }

    /**
     * Test attribute "supply_types"
     */
    public function testPropertySupplyTypes()
    {
    }

    /**
     * Test attribute "max_qps"
     */
    public function testPropertyMaxQps()
    {
    }

    /**
     * Test attribute "url_request"
     */
    public function testPropertyUrlRequest()
    {
    }

    /**
     * Test attribute "user_sync_url_options"
     */
    public function testPropertyUserSyncUrlOptions()
    {
    }

    /**
     * Test attribute "dsp_users_sync_url"
     */
    public function testPropertyDspUsersSyncUrl()
    {
    }

    /**
     * Test attribute "exchange"
     */
    public function testPropertyExchange()
    {
    }

    /**
     * Test attribute "subdomain_id"
     */
    public function testPropertySubdomainId()
    {
    }

    /**
     * Test attribute "subdomain_name"
     */
    public function testPropertySubdomainName()
    {
    }

    /**
     * Test attribute "datacenter"
     */
    public function testPropertyDatacenter()
    {
    }
}
