<?php
/**
 * EditCampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * EditCampaignTest Class Doc Comment
 *
 * @category    Class
 * @description EditCampaign
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EditCampaignTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EditCampaign"
     */
    public function testEditCampaign()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "iab_category"
     */
    public function testPropertyIabCategory()
    {
    }

    /**
     * Test attribute "time_zone"
     */
    public function testPropertyTimeZone()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "is_unlimited_budget"
     */
    public function testPropertyIsUnlimitedBudget()
    {
    }

    /**
     * Test attribute "daily_budget_is_unlimited"
     */
    public function testPropertyDailyBudgetIsUnlimited()
    {
    }

    /**
     * Test attribute "daily_budget"
     */
    public function testPropertyDailyBudget()
    {
    }

    /**
     * Test attribute "frequency_cap"
     */
    public function testPropertyFrequencyCap()
    {
    }

    /**
     * Test attribute "frequency_cap_type"
     */
    public function testPropertyFrequencyCapType()
    {
    }

    /**
     * Test attribute "frequency_cap_period"
     */
    public function testPropertyFrequencyCapPeriod()
    {
    }

    /**
     * Test attribute "macros_custom_data"
     */
    public function testPropertyMacrosCustomData()
    {
    }

    /**
     * Test attribute "attribution_enabled"
     */
    public function testPropertyAttributionEnabled()
    {
    }

    /**
     * Test attribute "conversion_pixel_id"
     */
    public function testPropertyConversionPixelId()
    {
    }

    /**
     * Test attribute "pixel_events_repeat"
     */
    public function testPropertyPixelEventsRepeat()
    {
    }

    /**
     * Test attribute "pixel_events_repeat_time"
     */
    public function testPropertyPixelEventsRepeatTime()
    {
    }

    /**
     * Test attribute "pixel_events_repeat_period"
     */
    public function testPropertyPixelEventsRepeatPeriod()
    {
    }

    /**
     * Test attribute "post_click_window_enabled"
     */
    public function testPropertyPostClickWindowEnabled()
    {
    }

    /**
     * Test attribute "post_click_window_period"
     */
    public function testPropertyPostClickWindowPeriod()
    {
    }

    /**
     * Test attribute "post_click_window"
     */
    public function testPropertyPostClickWindow()
    {
    }

    /**
     * Test attribute "post_view_window_enabled"
     */
    public function testPropertyPostViewWindowEnabled()
    {
    }

    /**
     * Test attribute "post_view_window_period"
     */
    public function testPropertyPostViewWindowPeriod()
    {
    }

    /**
     * Test attribute "post_view_window"
     */
    public function testPropertyPostViewWindow()
    {
    }

    /**
     * Test attribute "ssp_test_phase"
     */
    public function testPropertySspTestPhase()
    {
    }
}
