<?php
/**
 * EditSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * EditSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description EditSettings
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EditSettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EditSettings"
     */
    public function testEditSettings()
    {
    }

    /**
     * Test attribute "general"
     */
    public function testPropertyGeneral()
    {
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
    }

    /**
     * Test attribute "integrations"
     */
    public function testPropertyIntegrations()
    {
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
    }
}
