<?php
/**
 * InlineResponse20012Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse20012Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20012
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse20012Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20012"
     */
    public function testInlineResponse20012()
    {
    }

    /**
     * Test attribute "statuses"
     */
    public function testPropertyStatuses()
    {
    }

    /**
     * Test attribute "creative_statuses"
     */
    public function testPropertyCreativeStatuses()
    {
    }

    /**
     * Test attribute "creative_approval_statuses"
     */
    public function testPropertyCreativeApprovalStatuses()
    {
    }

    /**
     * Test attribute "creative_types"
     */
    public function testPropertyCreativeTypes()
    {
    }

    /**
     * Test attribute "creative_attributes"
     */
    public function testPropertyCreativeAttributes()
    {
    }

    /**
     * Test attribute "iab_categories"
     */
    public function testPropertyIabCategories()
    {
    }

    /**
     * Test attribute "time_zones"
     */
    public function testPropertyTimeZones()
    {
    }

    /**
     * Test attribute "frequency_cap_types"
     */
    public function testPropertyFrequencyCapTypes()
    {
    }

    /**
     * Test attribute "frequency_cap_periods"
     */
    public function testPropertyFrequencyCapPeriods()
    {
    }

    /**
     * Test attribute "pixel_events_repeats"
     */
    public function testPropertyPixelEventsRepeats()
    {
    }

    /**
     * Test attribute "repeat_merit_event_periods"
     */
    public function testPropertyRepeatMeritEventPeriods()
    {
    }

    /**
     * Test attribute "post_window_intervals"
     */
    public function testPropertyPostWindowIntervals()
    {
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
    }

    /**
     * Test attribute "budget_pacing_types"
     */
    public function testPropertyBudgetPacingTypes()
    {
    }

    /**
     * Test attribute "budget_pacing_budget_intervals"
     */
    public function testPropertyBudgetPacingBudgetIntervals()
    {
    }

    /**
     * Test attribute "frequency_cap_pacing_types"
     */
    public function testPropertyFrequencyCapPacingTypes()
    {
    }

    /**
     * Test attribute "frequency_cap_pacing_periods"
     */
    public function testPropertyFrequencyCapPacingPeriods()
    {
    }

    /**
     * Test attribute "frequency_cap_source_definition"
     */
    public function testPropertyFrequencyCapSourceDefinition()
    {
    }

    /**
     * Test attribute "rtb_supply_types"
     */
    public function testPropertyRtbSupplyTypes()
    {
    }

    /**
     * Test attribute "inventory_types"
     */
    public function testPropertyInventoryTypes()
    {
    }

    /**
     * Test attribute "target_any_or_all_of_segments"
     */
    public function testPropertyTargetAnyOrAllOfSegments()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "days"
     */
    public function testPropertyDays()
    {
    }

    /**
     * Test attribute "day_part_timezones"
     */
    public function testPropertyDayPartTimezones()
    {
    }

    /**
     * Test attribute "relation_type"
     */
    public function testPropertyRelationType()
    {
    }

    /**
     * Test attribute "site_list_relation_types"
     */
    public function testPropertySiteListRelationTypes()
    {
    }

    /**
     * Test attribute "sizes"
     */
    public function testPropertySizes()
    {
    }

    /**
     * Test attribute "add_audio"
     */
    public function testPropertyAddAudio()
    {
    }

    /**
     * Test attribute "secure_type_lists"
     */
    public function testPropertySecureTypeLists()
    {
    }

    /**
     * Test attribute "call_to_actions"
     */
    public function testPropertyCallToActions()
    {
    }

    /**
     * Test attribute "video_api_framework_types"
     */
    public function testPropertyVideoApiFrameworkTypes()
    {
    }

    /**
     * Test attribute "vast_types"
     */
    public function testPropertyVastTypes()
    {
    }

    /**
     * Test attribute "bid_type"
     */
    public function testPropertyBidType()
    {
    }

    /**
     * Test attribute "creative_events"
     */
    public function testPropertyCreativeEvents()
    {
    }

    /**
     * Test attribute "pixel_type"
     */
    public function testPropertyPixelType()
    {
    }

    /**
     * Test attribute "test_mode"
     */
    public function testPropertyTestMode()
    {
    }

    /**
     * Test attribute "permissions"
     */
    public function testPropertyPermissions()
    {
    }

    /**
     * Test attribute "data_storages"
     */
    public function testPropertyDataStorages()
    {
    }

    /**
     * Test attribute "impressions_counter_type"
     */
    public function testPropertyImpressionsCounterType()
    {
    }

    /**
     * Test attribute "targeting_delivery_types"
     */
    public function testPropertyTargetingDeliveryTypes()
    {
    }

    /**
     * Test attribute "rtb_integration_types"
     */
    public function testPropertyRtbIntegrationTypes()
    {
    }

    /**
     * Test attribute "messenger_types"
     */
    public function testPropertyMessengerTypes()
    {
    }

    /**
     * Test attribute "platform_types"
     */
    public function testPropertyPlatformTypes()
    {
    }

    /**
     * Test attribute "signup_roles"
     */
    public function testPropertySignupRoles()
    {
    }

    /**
     * Test attribute "user_details_where_find"
     */
    public function testPropertyUserDetailsWhereFind()
    {
    }

    /**
     * Test attribute "media_buying_experience"
     */
    public function testPropertyMediaBuyingExperience()
    {
    }

    /**
     * Test attribute "monthly_impressions_volume"
     */
    public function testPropertyMonthlyImpressionsVolume()
    {
    }

    /**
     * Test attribute "creative_image_types"
     */
    public function testPropertyCreativeImageTypes()
    {
    }

    /**
     * Test attribute "user_types"
     */
    public function testPropertyUserTypes()
    {
    }

    /**
     * Test attribute "publisher_payment_types"
     */
    public function testPropertyPublisherPaymentTypes()
    {
    }

    /**
     * Test attribute "datacenters"
     */
    public function testPropertyDatacenters()
    {
    }
}
