<?php
/**
 * NewCreativeDisplay3pasTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * NewCreativeDisplay3pasTest Class Doc Comment
 *
 * @category    Class
 * @description NewCreativeDisplay3pas
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NewCreativeDisplay3pasTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewCreativeDisplay3pas"
     */
    public function testNewCreativeDisplay3pas()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "iab_attr"
     */
    public function testPropertyIabAttr()
    {
    }

    /**
     * Test attribute "adomain"
     */
    public function testPropertyAdomain()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "display_width"
     */
    public function testPropertyDisplayWidth()
    {
    }

    /**
     * Test attribute "display_height"
     */
    public function testPropertyDisplayHeight()
    {
    }

    /**
     * Test attribute "audio"
     */
    public function testPropertyAudio()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "secure_type"
     */
    public function testPropertySecureType()
    {
    }

    /**
     * Test attribute "macros_custom_data"
     */
    public function testPropertyMacrosCustomData()
    {
    }
}
