<?php
/**
 * UserDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * UserDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description UserDetails
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserDetails"
     */
    public function testUserDetails()
    {
    }

    /**
     * Test attribute "field_of_activity"
     */
    public function testPropertyFieldOfActivity()
    {
    }

    /**
     * Test attribute "website_category"
     */
    public function testPropertyWebsiteCategory()
    {
    }

    /**
     * Test attribute "solvable_issue"
     */
    public function testPropertySolvableIssue()
    {
    }

    /**
     * Test attribute "media_buying_experience"
     */
    public function testPropertyMediaBuyingExperience()
    {
    }

    /**
     * Test attribute "monthly_impressions_volume"
     */
    public function testPropertyMonthlyImpressionsVolume()
    {
    }

    /**
     * Test attribute "where_find"
     */
    public function testPropertyWhereFind()
    {
    }

    /**
     * Test attribute "where_find_other"
     */
    public function testPropertyWhereFindOther()
    {
    }

    /**
     * Test attribute "monthly_budget"
     */
    public function testPropertyMonthlyBudget()
    {
    }

    /**
     * Test attribute "monthly_revenue"
     */
    public function testPropertyMonthlyRevenue()
    {
    }
}
