<?php
/**
 * KeywordListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * KeywordListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KeywordListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for keywordListsGet
     *
     * All Keyword Lists.
     *
     */
    public function testKeywordListsGet()
    {
    }

    /**
     * Test case for keywordListsKeywordListIdDelete
     *
     * Delete Keyword List.
     *
     */
    public function testKeywordListsKeywordListIdDelete()
    {
    }

    /**
     * Test case for keywordListsKeywordListIdGet
     *
     * Keyword List.
     *
     */
    public function testKeywordListsKeywordListIdGet()
    {
    }

    /**
     * Test case for keywordListsKeywordListIdKeywordsDelete
     *
     * Delete Keyword in Keyword List.
     *
     */
    public function testKeywordListsKeywordListIdKeywordsDelete()
    {
    }

    /**
     * Test case for keywordListsKeywordListIdKeywordsGet
     *
     * Keywords in Keyword List.
     *
     */
    public function testKeywordListsKeywordListIdKeywordsGet()
    {
    }

    /**
     * Test case for keywordListsKeywordListIdKeywordsPost
     *
     * Add Keywords to Keyword List.
     *
     */
    public function testKeywordListsKeywordListIdKeywordsPost()
    {
    }

    /**
     * Test case for keywordListsKeywordListIdPut
     *
     * Update Keyword List.
     *
     */
    public function testKeywordListsKeywordListIdPut()
    {
    }

    /**
     * Test case for keywordListsPost
     *
     * Create Keyword List.
     *
     */
    public function testKeywordListsPost()
    {
    }

    /**
     * Test case for keywordListsTopKeywordsGet
     *
     * Top Keyword Lists.
     *
     */
    public function testKeywordListsTopKeywordsGet()
    {
    }
}
