<?php
/**
 * SiteListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SiteListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SiteListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for siteListsGet
     *
     * All Site Lists.
     *
     */
    public function testSiteListsGet()
    {
    }

    /**
     * Test case for siteListsPost
     *
     * Create Site List.
     *
     */
    public function testSiteListsPost()
    {
    }

    /**
     * Test case for siteListsSiteListIdDelete
     *
     * Delete Site List.
     *
     */
    public function testSiteListsSiteListIdDelete()
    {
    }

    /**
     * Test case for siteListsSiteListIdGet
     *
     * Site List.
     *
     */
    public function testSiteListsSiteListIdGet()
    {
    }

    /**
     * Test case for siteListsSiteListIdPut
     *
     * Update Site List.
     *
     */
    public function testSiteListsSiteListIdPut()
    {
    }

    /**
     * Test case for siteListsSiteListIdSitesDelete
     *
     * Delete Site in Site List.
     *
     */
    public function testSiteListsSiteListIdSitesDelete()
    {
    }

    /**
     * Test case for siteListsSiteListIdSitesGet
     *
     * Sites in Site List.
     *
     */
    public function testSiteListsSiteListIdSitesGet()
    {
    }

    /**
     * Test case for siteListsSiteListIdSitesPost
     *
     * Add Sites to Site List.
     *
     */
    public function testSiteListsSiteListIdSitesPost()
    {
    }

    /**
     * Test case for siteListsTopSitesGet
     *
     * Top Site Lists.
     *
     */
    public function testSiteListsTopSitesGet()
    {
    }
}
