<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for adminAdvertisersGet
     *
     * All Advertisers.
     *
     */
    public function testAdminAdvertisersGet()
    {
    }

    /**
     * Test case for adminAgenciesGet
     *
     * All Agencies.
     *
     */
    public function testAdminAgenciesGet()
    {
    }

    /**
     * Test case for adminOrganizationsGet
     *
     * All Organizations **Only for ROOT**.
     *
     */
    public function testAdminOrganizationsGet()
    {
    }

    /**
     * Test case for adminPublishersGet
     *
     * All Publishers.
     *
     */
    public function testAdminPublishersGet()
    {
    }

    /**
     * Test case for adminUsersGet
     *
     * All Users.
     *
     */
    public function testAdminUsersGet()
    {
    }

    /**
     * Test case for adminUsersUserIdGet
     *
     * User attached roles **Only for Root/Admins**.
     *
     */
    public function testAdminUsersUserIdGet()
    {
    }

    /**
     * Test case for meBonusinfoGet
     *
     * Get checklist for bonus.
     *
     */
    public function testMeBonusinfoGet()
    {
    }

    /**
     * Test case for meDetailsPost
     *
     * Set User Details.
     *
     */
    public function testMeDetailsPost()
    {
    }

    /**
     * Test case for meGet
     *
     * Get Loggedin User Info.
     *
     */
    public function testMeGet()
    {
    }

    /**
     * Test case for meGetbonusGet
     *
     * Get bonus when checklist is done.
     *
     */
    public function testMeGetbonusGet()
    {
    }

    /**
     * Test case for mePleaseDelete
     *
     * Delete User.
     *
     */
    public function testMePleaseDelete()
    {
    }

    /**
     * Test case for meRolesGet
     *
     * Get owned roles.
     *
     */
    public function testMeRolesGet()
    {
    }

    /**
     * Test case for paymentAddPut
     *
     * Add payment  **Only for Root/Admins/Agencies**.
     *
     */
    public function testPaymentAddPut()
    {
    }

    /**
     * Test case for paymentGet
     *
     * Users balance info **Only for Root/Admins/Agencies**.
     *
     */
    public function testPaymentGet()
    {
    }

    /**
     * Test case for registerPost
     *
     * Register a new user.
     *
     */
    public function testRegisterPost()
    {
    }

    /**
     * Test case for usersGet
     *
     * Get All Users.
     *
     */
    public function testUsersGet()
    {
    }

    /**
     * Test case for usersPost
     *
     * Create User..
     *
     */
    public function testUsersPost()
    {
    }

    /**
     * Test case for usersUserIdApprovePut
     *
     * Approve/Unapprove user.
     *
     */
    public function testUsersUserIdApprovePut()
    {
    }

    /**
     * Test case for usersUserIdGet
     *
     * Get User.
     *
     */
    public function testUsersUserIdGet()
    {
    }

    /**
     * Test case for usersUserIdPermissionsGet
     *
     * Get User Permissions.
     *
     */
    public function testUsersUserIdPermissionsGet()
    {
    }

    /**
     * Test case for usersUserIdPut
     *
     * Update User.
     *
     */
    public function testUsersUserIdPut()
    {
    }

    /**
     * Test case for usersUserIdResourcesGet
     *
     * Get User Resources.
     *
     */
    public function testUsersUserIdResourcesGet()
    {
    }
}
