<?php
/**
 * UseragentListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PLATFORM.IO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UseragentListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UseragentListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for useragentListsGet
     *
     * All Useragent Lists.
     *
     */
    public function testUseragentListsGet()
    {
    }

    /**
     * Test case for useragentListsPost
     *
     * Create Useragent List.
     *
     */
    public function testUseragentListsPost()
    {
    }

    /**
     * Test case for useragentListsUseragentListIdDelete
     *
     * Delete Useragent List.
     *
     */
    public function testUseragentListsUseragentListIdDelete()
    {
    }

    /**
     * Test case for useragentListsUseragentListIdGet
     *
     * Useragent List.
     *
     */
    public function testUseragentListsUseragentListIdGet()
    {
    }

    /**
     * Test case for useragentListsUseragentListIdItemsDelete
     *
     * Delete Useragent in Useragent List.
     *
     */
    public function testUseragentListsUseragentListIdItemsDelete()
    {
    }

    /**
     * Test case for useragentListsUseragentListIdItemsGet
     *
     * Useragents in Useragent List.
     *
     */
    public function testUseragentListsUseragentListIdItemsGet()
    {
    }

    /**
     * Test case for useragentListsUseragentListIdItemsPost
     *
     * Add Useragents to Useragent List.
     *
     */
    public function testUseragentListsUseragentListIdItemsPost()
    {
    }

    /**
     * Test case for useragentListsUseragentListIdPut
     *
     * Update Useragent List.
     *
     */
    public function testUseragentListsUseragentListIdPut()
    {
    }
}
